build_web:
  stage: build
  image: cirrusci/flutter:stable
  before_script:
    - flutter clean
    - flutter pub get
  script:
    - flutter build web --release
  artifacts:
    paths:
      - build/web

pages:
  stage: deploy
  script:
    - cp -r build/web public
    - cp -r assets/images public
  artifacts:
    paths:
      - public
  only:
    - live