variables:
  GIT_SUBMODULE_STRATEGY: recursive
  NOMAD_HTTP_ADDR: "http://65.21.92.186:4646"
  CI_REGISTRY: "registry.gitlab.com/love4src"
  PATH: "/tmp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

services:
  - docker:dind

build_live:
  stage: build
  image: docker:stable
  script:
    - echo "$DEPLOY_DOCKER_PASS" | docker login -u "$DEPLOY_DOCKER_USER" --password-stdin registry.gitlab.com
    - docker build --pull --tag "${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA}" .
    - docker push "${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA}"
  only:
    - live

deploy_live:
  stage: deploy
  image: hashicorp/levant:0.3.0
  script:
    - levant deploy -address="${NOMAD_HTTP_ADDR}" -var "commit_sha=${CI_COMMIT_SHA}" carbon-prod.hcl
  only:
    - live


build_web:
  stage: build
  image: cirrusci/flutter:stable
  before_script:
    - flutter clean
    - flutter pub get
  script:
    - flutter build web --release
  artifacts:
    paths:
      - build/web
  only:
    - pages

pages:
  stage: deploy
  script:
    - cp -r build/web public
    - cp -r assets/images public/assets
  artifacts:
    paths:
      - public
  only:
    - pages